apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mycrd
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/lyc-handson-aws/handson-topic10-operator