apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mycrd
  namespace: flux-system
spec:
  interval: 24h
  path: ./config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: mycrd